FROM bitnamilegacy/spark:3.5.1

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash curl build-essential python3-pip \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
ENV PYTHONPATH=/app
WORKDIR /app
COPY . /app
USER 1001
